# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeac70e2df4bf2341adbd1c8d45cc7a14e6b0320f9fe413c67ae0a256db5526832924f35770ed843e90b19426563a732cf0f06d8fb0feae5650879b7d6a04f41

test:
  secret_key_base: 872090078f3e79b5270197ace597a8b0256ada403d48623a6b68a4a00f3997ff3bf1129d40b15a344c58ff906917253253d6d3d460de8d33d356df0790a8ff40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
